### ISSUE TITLE
Choose a line color

### ISSUE THREAD

**Issue by skoop** [Ingewikkeld/energyforanthony#5]
Right now all lines are dark blue, but it would be cool if we could allow users to pick their own color for the line, as color may signify the type of energy the user wants to send to Anthony.

Right now, I've hooked in on the existing javascript from http://php.ug/, and I'm not sure how we can pass a color that could be in the database into the javascript correctly to be able to set the color.

**Comment by mvriel** [comment]
I'll get this one

**Comment by mvriel** [comment]
Fixed with PR #23
