### ISSUE TITLE
Anthony's pin should perhaps also have a popup

### ISSUE THREAD

**Issue by skoop** [Ingewikkeld/energyforanthony#6]
At least it should have his name on hover. Perhaps we also want some information as a popup there.

**Comment by marjoleinve** [comment]
C. Anthony Martignetti,
I suggest adding links to his website camstories, FB profile and twitter when available. Perhaps a picture too, when implemented.

**Comment by Gwendolyn68** [comment]
I'll work on this one

**Comment by Gwendolyn68** [comment]
Solved this via #22

**Comment by skoop** [comment]
:+1:
