### ISSUE TITLE
Location finder: improvements and userfriendlyness

### ISSUE THREAD

**Issue by marjoleinve** [Ingewikkeld/energyforanthony#8]
Test and improve the ability to find locations based on town, zipcode or address. (new api?)
Also: could be more userfriendly in the form? Users suggested drag&drop interface for the pins but that's probably not realistic now.

**Comment by mvriel** [comment]
Please check the new submission form after pimping; there are more UX improvements to be done but you can already pass your address

**Comment by marjoleinve** [comment]
<3 thanks
